### ISSUE TITLE
Does Sigma allow dots and/or dashes in tags? (sigmahq.io documentation versus pySigma validation)

### ISSUE THREAD

**Issue by Karneades** [SigmaHQ/sigma-specification#127]
Hi all, according to https://github.com/SigmaHQ/pySigma/blob/main/sigma/validators/core/tags.py#L114 CVE are checked for dots and CAR for dashes which is also documented in https://github.com/SigmaHQ/sigma-specification/blob/main/Tags_specification.md. But according to https://sigmahq.io/docs/basics/rules.html both are valid for both namespaces.

What is the current state and what should be adapted to match the spec? Should the docs in https://github.com/SigmaHQ/sigmahq.github.io/blob/main/docs/basics/rules.md#tags--metadata-tags- be changed?

**Comment by thomaspatzke** [comment]
Transferred to specification, appears more appropriate here to me.

**Comment by nasbench** [comment]
I would also choose dashes. i'll make the necessary changes in the specs

**Comment by Karneades** [comment]
Amd then fix https://github.com/SigmaHQ/pySigma/blob/main/sigma/validators/core/tags.py#L114 as well for dashes?

**Comment by nasbench** [comment]
This is fixed in https://github.com/SigmaHQ/sigma-specification/pull/139 and in pySigma in https://github.com/SigmaHQ/pySigma/pull/248

**Comment by Karneades** [comment]
Thanks!
