### ISSUE TITLE
Version number in Sigma specification doc doesn't match to history

### ISSUE THREAD

**Issue by alexott** [SigmaHQ/sigma-specification#129]
The [History](https://github.com/alexott/sigma-specification/blob/main/Sigma_specification.md#history) specifies version as 1.0.4 and release in 2023rd, while version in the begin of the docs shows 1.0.3 and release in 2022nd:

```
    Version 1.0.3
    Release date 2022/12/28
```

**Comment by nasbench** [comment]
Thanks for reporting this. This will be fixed in V2 soon. See https://github.com/SigmaHQ/sigma-specification/pull/139
