### ISSUE TITLE
OpenSSH product and service mapping from Windows logs

### ISSUE THREAD

**Issue by mdecrevoisier** [SigmaHQ/sigma-specification#13]
Hi,
I was looking for the product and service mapping that I should use in regards of the Windows Event Channel **'OpenSSH/Operational'**, but I couldn't find anything except in the Linux part. Could you clarify which mapping we should use for this channel ? Please not that this is not related to the WSL topic. This is a native Channel that can be found in Windows 10.

Maybe a suggestion:
-   product: windows
-   service: sshd

SIGMA log sources: https://github.com/SigmaHQ/sigma/wiki/Log-Sources
My Windows OpenSSH rule: https://github.com/mdecrevoisier/SIGMA-detection-rules/blob/main/windows-openssh/win-os-OpenSSH%20server%20listening.yaml

Many thanks
Michel de Crevoisier

![ssh windows](https://user-images.githubusercontent.com/52909656/188973055-fe609296-2438-4432-bdfc-98a37c89c861.png)

**Comment by Neo23x0** [comment]
I anyone provides these mappings in every config, we can merge a pull request
