### ISSUE TITLE
Semi-Dead links to Sigma Correlations

### ISSUE THREAD

**Issue by jonathan-s** [SigmaHQ/sigma-specification#134]
The sigma correlation speciffication links in the following document https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md leads to this wiki page [Sigma Correlations specification](https://github.com/SigmaHQ/sigma/wiki/Specification:-Sigma-Correlations) that wiki page does not contain the sigma correlation specification. 

It would be helpful to link to the correct paragraph / page for this.

**Comment by nasbench** [comment]
This issue has been resolved in the spec V2. Will get merged into master soon.
