### ISSUE TITLE
How to use Sigma correlations

### ISSUE THREAD

**Issue by alexpwns** [SigmaHQ/sigma-specification#15]
I was reading through the wiki and noticed this line, "Aggregations in the condition are deprecated and will be replaced with Sigma correlations.", but can't seem to find any additional information on how to use Sigma correlations. Is there any additional info on Sigma correlations?

**Comment by frack113** [comment]
Hello,
https://github.com/SigmaHQ/sigma-specification/blob/main/wip/Sigma_Correlations.md

**Comment by nasbench** [comment]
Information on correlation can be found in the following locations:
- https://github.com/SigmaHQ/sigma-specification/tree/version_2
- https://blog.sigmahq.io/introducing-sigma-correlations-52fe377f2527
