### ISSUE TITLE
What flavor a regular expressions does sigma use?

### ISSUE THREAD

**Issue by YamatoSecurity** [SigmaHQ/sigma-specification#25]
It is not specified (AFAIK) which flavor of regular expressions sigma rules use. PCRE2? PCRE?, etc...?

Regex parsing will change depending on the programming language, etc... so this should probably be defined in the specification so that it is clear what to use.

**Comment by thomaspatzke** [comment]
It's indeed not specified and currently existing conversion logic (pySigma, sigmac) passes it through to the query. I think PCRE is currently most prevalent in most query languages and other software, but usage of advanced features in rules could cause incompatibilities. Therefore I suggest to restrict to a basic subset of features, more specific:

* `.` placeholder
* `[a-z]` character sets with negation syntax `[^...]` but no character class syntax like `[:...:]`.
* `*`, `?` and `+` quantifiers.
* `{min,max}` repetition syntax.
* Grouping with `(...)`, omitting all modifiers like lookahead/behind etc.
* OR operator `|` inside of groups.

**Comment by thomaspatzke** [comment]
I've removed the question from the title, it's underspecified and therefore an issue 😉
