### ISSUE TITLE
Add log source (diagnosis-scripted) to taxonomy

### ISSUE THREAD

**Issue by H-cognna** [SigmaHQ/sigma-specification#30]
Hello

https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/diagnosis/scripted/win_diagnosis_scripted_load_remote_diagcab.yml

from this rule:
service: diagnosis-scripted

and diagnosis-scripted is not mentioned in the taxonomy, could you please add it?

**Comment by frack113** [comment]
Added in https://github.com/SigmaHQ/sigma-specification/blob/main/Taxonomy_1_3_0.md
