### ISSUE TITLE
Taxonomy update to support BitLocker Channel

### ISSUE THREAD

**Issue by mdecrevoisier** [SigmaHQ/sigma-specification#33]
Hi,
Current Sigma specifications for Windows taxonomy do not include the support for Channel: 'Microsoft-Windows-BitLocker/BitLocker Management'.  I would suggest to add it so community can take some benefits in terms of detections.

Suggestion:

windows | product: windows category: bitlocker| Channel: Microsoft-Windows-BitLocker/BitLocker Management
-- | -- | --

EVTX sample: https://github.com/mdecrevoisier/EVTX-to-MITRE-Attack/tree/master/TA0040-Impact/T1486-Data%20Encrypted%20for%20Impact
SIGMA rule: https://github.com/mdecrevoisier/SIGMA-detection-rules/blob/main/windows-bitlocker/win-os-BitLocker%20massive%20feature%20activation%20(native).yaml  

Best regards
mdecrevoisier

**Comment by nasbench** [comment]
Thanks for the suggestion. Will add the channel later today.

**Comment by mdecrevoisier** [comment]
Sure. Just for information there are 2 channels under the BitLocker folder: "BitLocker Management" (enabled per default) and "BitLocker Operational" (disabled per default, no real or known interest at the moment).
