### ISSUE TITLE
Homepage for Sigma Specification cutting off characters

### ISSUE THREAD

**Issue by joshnck** [SigmaHQ/sigma-specification#61]
![image](https://user-images.githubusercontent.com/16333554/217077312-2b98d746-9f96-486a-8d38-8c598a95709b.png)
![image](https://user-images.githubusercontent.com/16333554/217077405-854ce5c5-a3a8-4cd9-ab56-c6d88a0cdb55.png)

As you can see I've got plenty of space for that frame to expand, but it is still shrinking the frame to not include the final 'n' that should be there.

If it matters, I am using Edge.

**Comment by nasbench** [comment]
cc @frack113
